server:
  port: 9090
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_mall?serverTimezone=GMT%2b8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
